name: Chunkfreeze
version: @version@
main: dev.wnuke.blazenarchy.chunkfreeze.Chunkfreeze
api-version: 1.13
authors: [wnuke]
description: Plugin to stop a chunk from saving based on an item or block placed in it.
website: blazenarchy.net
commands:
  dupechunk:
    description: The command for stopping chunks from saving.
    aliases: [dupechunk, dc, dupe]
permissions:
  dupechunk.freeze:
    description: Freezes chunks
    default: false
  dupechunk.unfreeze:
    description: Unfreezes chunks
    default: false
  dupechunk.help:
    description: Displays tutorial on duping
    default: false
  dupechunk.list:
    description: Lists frozen chunks
    default: false
  dupechunk.info:
    description: Displays info about the plugin
    default: true
