name: Chunkfreeze
version: @version@
main: dev.wnuke.blazenarchy.chunkfreeze.Chunkfreeze
api-version: 1.13
authors: [wnuke]
description: Plugin to stop a chunk from saving based on an item or block placed in it.
website: blazenarchy.net
commands:
  freezechunk:
    description: Freezes the chunk you are currently standing in.
    usage: /<command>
